server:
  port: 8081

logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.tianyalan: INFO

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@localhost:8761/eureka/

spring:
  application:
    name: cardservice
  cloud:
    config:
      enabled: true
      uri: http://localhost:8888

  security:
    oauth2:
      resource:
        userInfoUri: http://localhost:8080/userinfo
    user:
      name: ysan
      password: pwd123
