server:
  port: 8080

spring:
  application:
    name: authservice
  profiles:
    active:
      default
  security:
    user:
      name: ysan
      password: pwd123

logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.tianyalan: INFO

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@localhost:8761/eureka/
