server:
  port: 8761


spring:
  application:
    name: eurekaserver
  security:
    user:
      name: ysan
      password: pwd123


eureka:
  client:
    healthcheck:
      enabled: true
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@localhost:8761/eureka/

  server:
    waitTimeInMsWhenSyncEmpty: 0
    # 关闭自我保护
    enable-self-preservation: false
    # 清理服务器
    eviction-interval-timer-in-ms: 5000


logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.tianyalan: INFO
